name: build and deploy

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.web-app-service
          key: ${{ runner.os }}-web-app-service

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        run: echo SHA_SHORT=`(git rev-parse --short HEAD)` >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: false
          tags: pakhom/helloworld:${{ env.SHA_SHORT }}
          cache-from: type=local,src=/tmp/.web-app-service
          cache-to: type=local,dest=/tmp/.web-app-service-new
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'pakhom/helloworld:${{ env.SHA_SHORT }}'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Push image
        run: docker push pakhom/helloworld:${{ env.SHA_SHORT }}

      - name: Move cache
        run: |
          rm -rf /tmp/.web-app-service
          mv /tmp/.web-app-service-new /tmp/.web-app-service

  deploy:
    name: Deploy service
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout...
        uses: actions/checkout@v2

      - uses: medyagh/setup-minikube@master

      - uses: azure/setup-helm@v3

      - name: Deploy app
        run: helm upgrade --install -n default --set image.tag=${{ env.SHA_SHORT }} --wait hello .chart

      - name: Check application
        run: |
          helm list -n default
          kubectl get all -n default
          kubectl port-forward svc/hello 8080:8080 &
          sleep 10
          curl 127.0.0.1:8080


